[
    "1.  Site folder available with index.", [cite: 1]
    "2.  Checklist completed and signed by the installation supervisor/Hardware audit available.", [cite: 2]
    "3.  Asset - floor plan - rack layout - IP plan - power plan should be available.", [cite: 2]
    "4.  Documents should be approved before installation.", [cite: 3]
    "5.  The cabinet shall be installed according to floor plan.", [cite: 3]
    "6.  The cabinet shall be installed and fixed very well.", [cite: 4]
    "7.  The cabinet should be separated from support and buzzer test failed (BSC).", [cite: 5]
    "8.  Boards of rack could be plugged and pulled out easily.", [cite: 6]
    "9.  Patch panel, OCDF and ODF unit shall be installed in correct position of rack or open Rack.", [cite: 7]
    "10. Racks should fix to each other in standard method (core and R-BSC).", [cite: 8]
    "11. Cabinets shall be labeled at R_BSC and core sites.", [cite: 9]
    "12. Doors adjusted to open and close easily.", [cite: 9]
    "13. The installation of racks complies with the quakeproof requirements. The vertical deviation is less than 3 mm [0.11 in.].", [cite: 10]
    "14. Support of rack should install completely with isolation equipment’s at BSCs.", [cite: 11]
    "15. When a cabinet is installed on the ESD-preventive floor, the feet of the supports are fastened by the expansion bolts that are fixed firmly on the floor. The insulating plate, plain washer, spring washer, nut (bolt) is installed in correct order.", [cite: 12, 13]
    "16. All the screws are fastened tightly. Each screw has a flat washer and a spring washer. The two washers are fixed in correct order.", [cite: 15, 16]
    "17. The cabinets in a row are placed in the same line in a close and neat way.", [cite: 16]
    "18. Each row of cabinets is placed in a line, and the deviation is less than 5 mm [0.19 in.] (Core sites).", [cite: 17]
    "19. The side panel, front door, and back door are installed correctly.", [cite: 18]
    "20. The front door and back door can be opened and closed smoothly (shelters).", [cite: 19]
    "21. The front door, back door and side panel are tidy without any stain or handprint (shelters).", [cite: 19, 20]
    "22. The cable-through holes of the cabinet must be covered.", [cite: 21]
    "23. There are no surplus cable ties, stubs or other sundries in the cabinets.", [cite: 22]
    "24. The ESD-preventive wrist strap must be inserted into the ESD-preventive mounting hole of the cabinet (shelters).", [cite: 23]
    "25. Waterproof and anticorrosive measures should be adopted for outdoor equipment.", [cite: 24]
    "26. The cabinet labels are affixed in a tidy manner.", [cite: 25]
    "27. Power cable should be fixed very well in power equipment side and rack side.", [cite: 26]
    "28. Blue cables are “–48 V” or “–60 V” power cables. Black cables are RTN power cables.", [cite: 27]
    "29. Blue cables are –48 V or –60 V power cables. Black cables are RTN power cables.", [cite: 27, 28]
    "30. Yellowish green cables (upon the customer's request) are PGND cables.", [cite: 29]
    "31. The surplus part of the power cables and protection grounding cables must be cut off.", [cite: 30]
    "32. Cabinet power redundancy check.", [cite: 31]
    "33. All the power cables and grounding cables are connected firmly. The polarity is correct. The cables are in good contact.", [cite: 31, 32]
    "34. Power cable of cabinet should be installed according to approved power plan.", [cite: 32]
    "35. Power cable shall be labeled properly in both rack and power equipment side.", [cite: 33]
    "36. Grounding cable of cabinet and DDF/ODF shall be installed very well, in both equipment and grounding bar side.", [cite: 34]
    "37. Cables installed and routed neatly in cable ladders.", [cite: 35]
    "38. Grounding cable of cabinet and DDF/ODF shall be labeled. Labels should show destination of opposite end of the cable.", [cite: 35, 36]
    "39. DC Power cables, grounding cables, and signal cables are bound and laid separately. Power cables, grounding cables, and signal cables outside the cabinets are more than 3 cm [1.2 in.] away from each other.", [cite: 37, 38]
    "40. Power cable and grounding cable shall be tightened properly.", [cite: 39]
    "41. Power fuses should use based on approved plan.", [cite: 39]
    "42. When two or more cables are installed on one wire post, the cross-installation method or the back-to-back installation method must be adopted. When cables overlap each other, the OT terminal must be curved 45 degrees or 90 degrees. In overlapping installation, the bigger OT terminal must be installed in lower place, and the smaller OT terminal must be installed in upper place.", [cite: 40, 41, 42]
    "43. Power cable should be fixed very well in power equipment side and rack side.", [cite: 43]
    "44. The Fiber patch cords should be arranged according to engineering design document.", [cite: 44]
    "45. No damage or rupture in Fiber patch cords.", [cite: 45]
    "46. The cables cannot be stretched at bending area.", [cite: 45]
    "47. The fiber patch cords should be protected and installed in suitable duct or fiber ladder out of cabinet.", [cite: 46]
    "48. Outdoor rack has suitable battery backup.", [cite: 47]
    "49. Outdoor rack has suitable cooling and enough free space for air circulation.", [cite: 47]
    "50. Outdoor fiber should use at outdoor area at sites inside conduit and using indoor fiber isn’t acceptable at all.", [cite: 48]
    "51. The fiber patch cords should be arranged properly inside of cabinet and ODF-PP rack.", [cite: 49]
    "52. The fiber patch cords should be labeled in both cabinet and ODF-PP side.", [cite: 50]
    "53. Fibers and LAN cables need label in midway each 2m.", [cite: 51]
    "54. Patch cord shall be tightened properly, patch cord should not damage by wire clip.", [cite: 52]
    "55. The fiber patch cords should be in normal length and long fiber is not accepted (50cm only as extra).", [cite: 53]
    "56. Patch cord shall be tightened properly by soft wrap each 30 cm or helical and tie wrap is forbidden (helical not allowed at switch site).", [cite: 54]
    "57. Plan of ODF shall be filled and attached on side of ODF RACK.", [cite: 55]
    "58. LAN cables should be SFTP near power cables.", [cite: 56]
    "59. Under patch panel installing cable management is mandatory.", [cite: 57]
    "60. Extra fiber should loop around gurgles and loop in duct or on ladder isn’t acceptable.", [cite: 57]
    "61. All cables should be labeled as well in both sides.", [cite: 58]
    "62. Labels should be two sided and each side contains information.", [cite: 59]
    "63. Fibers should place inside duct in BSC or on special ladder in core sites and fasten by soft wrap each 30 cm or helically.", [cite: 60]
    "64. Fiber groups should be labeled inside duct each 2m.", [cite: 61]
    "65. Plan of ODF or PP shall be filled and attached on side of sub-RACK.", [cite: 62]
    "66. Clock cable shall be installed and connected, if EXTERNAL clock is required.", [cite: 63]
    "67. Clock cable shall be labeled properly in both sides.", [cite: 64]
    "68. Ethernet cable shall be installed and connected.", [cite: 64]
    "69. Ethernet cable shall be labeled properly in both sides same as fiber method.", [cite: 65]
    "70. Ethernet cable shall be in normal length.", [cite: 66]
    "71. Cables are properly seated, all the cables have been protected from sharp edges, all the cables dressed to avoid damage to the cables.", [cite: 66, 67]
    "72. All cables must be uniform, neat and must not be intertwined.", [cite: 67]
    "73. All the signal cables have passed the continuity check before they are laid.", [cite: 68]
    "74. The cabling route complies with the engineering design. Signal cables and power cables are bound separately.", [cite: 69]
    "75. The cables cannot be stretched at bending area.", [cite: 70]
    "76. Cables must be laid smoothly and orderly. Cables inside the cabinets cannot be twisted. Cables outside the cabinets must be bound separately based on the cabinet that the cables belong to.", [cite: 70, 71]
    "77. Keep redundant cables for future use. Cable ties are well tied and trimmed without sharp ends.", [cite: 72]
    "78. When the optical fibers are laid outside the cabinet, use the protection tube and ensure that two ends of the tube are bound and fixed. In addition, polish the ends of the protection tube (on outdoor fibers at site).", [cite: 73, 74]
    "79. Ducts should have standard junction in standard mode (BSC).", [cite: 75]
    "80. Install caps to protect the temporarily unused fibers.", [cite: 76]
    "81. Cables are bound correctly. Cable ties are in correct positions and are spaced properly.", [cite: 76, 77]
    "82. If a cable has the fastening screws, fasten the screws.", [cite: 77]
    "83. All cables and pipes should fix on ladder.", [cite: 78]
    "84. The Fiber patch cords should be arranged according to engineering design document.", [cite: 78]
    "85. No damage or rupture in Fiber patch cords.", [cite: 79]
    "86. The cables cannot be stretched at bending area.", [cite: 79, 80]
    "87. The fiber patch cords should be protected and installed in suitable duct or fiber ladder out of cabinet.", [cite: 80]
    "88. All cables and fibers should dismantle by rack in dismantling time.", [cite: 81]
    "89. All materials should deliver to WH in dismantling visit." [cite: 82]
]
